version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

    networks:
      - local
  app:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
    depends_on: 
      - db
    networks:
      - local
  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    networks:
      - local

networks:
  local:
    driver: bridge